//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bautismo
    {
        public int id { get; set; }
        public System.DateTime fechaBautismo { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int sexo { get; set; }
        public string nombrePadre { get; set; }
        public string nombreMadre { get; set; }
        public string nombrePadrino { get; set; }
        public string nombreMadrina { get; set; }
        public string parroquia { get; set; }
        public string municipio { get; set; }
        public string ciudad { get; set; }
        public int idEstado { get; set; }
        public Nullable<int> idMinistro { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual ministro ministro { get; set; }
    }
}
