//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletas.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bautismo> bautismos { get; set; }
        public virtual DbSet<catequista> catequistas { get; set; }
        public virtual DbSet<confirmacione> confirmaciones { get; set; }
        public virtual DbSet<empleado> empleados { get; set; }
        public virtual DbSet<estado> estados { get; set; }
        public virtual DbSet<estatu> estatus { get; set; }
        public virtual DbSet<matrimonio> matrimonios { get; set; }
        public virtual DbSet<ministro> ministros { get; set; }
        public virtual DbSet<parroco> parrocoes { get; set; }
        public virtual DbSet<primerasComunione> primerasComuniones { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<parroquia> parroquias { get; set; }
    }
}
