//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class catequista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catequista()
        {
            this.primerasComuniones = new HashSet<primerasComunione>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public Nullable<decimal> telefono { get; set; }
        public string correoElectronico { get; set; }
        public string direccion { get; set; }
        public int idEstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<primerasComunione> primerasComuniones { get; set; }
        public virtual estatu estatu { get; set; }
    }
}
