//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class matrimonio
    {
        public int id { get; set; }
        public System.DateTime fechaMatrimonio { get; set; }
        public string nombreEsposo { get; set; }
        public string apellidoPaternoEsposo { get; set; }
        public string apellidoMaternoEsposo { get; set; }
        public string nombreEsposa { get; set; }
        public string apellidoPaternoEsposa { get; set; }
        public string apellidoMaternoEsposa { get; set; }
        public string parroquiaProcedencia { get; set; }
        public string padrinoVelacion { get; set; }
        public string madrinaVelacion { get; set; }
        public string padrinoAnillos { get; set; }
        public string madrinaAnillos { get; set; }
        public string padrinoArras { get; set; }
        public string madrinaArras { get; set; }
        public int idParroco { get; set; }
        public Nullable<int> idMinistro { get; set; }
    
        public virtual ministro ministro { get; set; }
        public virtual parroco parroco { get; set; }
    }
}
