//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class primerasComunione
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public System.DateTime fechaComunion { get; set; }
        public string nombrePadrino { get; set; }
        public string nombreMadrina { get; set; }
        public int idCatequista { get; set; }
        public int idParroco { get; set; }
    
        public virtual catequista catequista { get; set; }
        public virtual parroco parroco { get; set; }
    }
}
